### ISSUE TITLE
better error message when phpXX-xml is missing

### ISSUE THREAD

**Issue by kurtseifried** [WP2Static/static-html-output-plugin#119]
better error message when phpXX-xml is missing, right now it just does the:

Failed during "Crawling initial file list", please consult the Help tab for where to get assistance.

enabled debug and found:

[Tue Jul 07 04:02:29.259128 2020] [php7:error] [pid 2233] [client 1.2.3.4:22672] PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/html/wp-content/plugins/static-html-output-plugin/plugin/WP2Static/HTMLProcessor.php:2\nStack trace:\n#0 /var/www/html/wp-content/plugins/static-html-output-plugin/plugin/WP2Static/SiteCrawler.php(2): HTMLProcessor->processHTML('<!doctype html>...', 'http://network....')\n#1 //var/www/html/wp-content/plugins/static-html-output-plugin/plugin/WP2Static/SiteCrawler.php(2): SiteCrawler->loadFileForProcessing()\n#2 /var/www/html/wp-content/plugins/static-html-output-plugin/plugin/WP2Static/SiteCrawler.php(2): SiteCrawler->crawlABitMore()\n#3 /var/www/html/wp-content/plugins/static-html-output-plugin/plugin/WP2Static/SiteCrawler.php(2): SiteCrawler->crawl_site()\n#4 /var/www/html/wp-content/plugins/static-html-output-plugin/plugin/WP2Static/SiteCrawler.php(2): SiteCrawler->__construct()\n#5 /var/www/html/wp-content/plugins/static-html-output- in /var/www/html/wp-content/plugins/static-html-output-plugin/plugin/WP2Static/HTMLProcessor.php on line 2, referer: https://someurl/wp-admin/admin.php?page=wp2static

which indicates phpXX-xml is missing. A cleaner error (e.g. a check) would be nice, thanks.

**Comment by thegulshankumar** [comment]
Thanks for the feedback
