### ISSUE TITLE
Add "BunnyCDN Storage Region" option to support BunnyCDN beta API / upcoming changes

### ISSUE THREAD

**Issue by thegulshankumar** [WP2Static/static-html-output-plugin#44]
For BunnyCDN, please add a dropdown for these regions to prevent upload failing.

![image](https://user-images.githubusercontent.com/23408127/82210751-46e1c280-992d-11ea-8325-0db47db8e3e7.png)

**Europe (Falkenstein)**
`storage.bunnycdn.com`

**US West (New York)**
`ny.storage.bunnycdn.com`

**Asia Singapore**
`sg.storage.bunnycdn.com`

**Comment by leonstafford** [comment]
I didn't get a response back from my request for Beta access to Bunny.

Are those the only other options we need to include to support the new beta? Also a different beta API URL?

**Comment by thegulshankumar** [comment]
Just changing hostname works. So I feel, what we need is 

Select Region => Connect to that hostname while uploading.

**Comment by leonstafford** [comment]
perfect! Are those the only regions they are offering in Beta now?

**Comment by thegulshankumar** [comment]
Yes, exactly.

**Comment by leonstafford** [comment]
[static-html-output-plugin-6.6.10.zip](https://github.com/WP2Static/static-html-output-plugin/files/4651353/static-html-output-plugin-6.6.10.zip)

^ @thegulshankumar, could you please try that at your convenience. I haven't gone all the way through testing, but it should work, defaulting to the EU endpoint if nothing is chosen.

"Test" buttons for all deployment methods still need fixing in this project

**Comment by thegulshankumar** [comment]
When I tested with Singapore region.

Please refer to the last line directly. I included full logs to show few more stuffs that might help.
```
PHP Fatal error: Uncaught TypeError: Argument 1 passed to StaticHTMLOutput\Controller::activate() must be of the type bool, null given, called in /usr/html/wp-includes/class-wp-hook.php on line 287 and defined in /usr/html/wp-content/plugins/static-html-output-plugin/src/Controller.php:115

Stack trace:

#0 /usr/html/wp-includes/class-wp-hook.php(287): StaticHTMLOutput\Controller::activate(NULL)

#1 /usr/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)

#2 /usr/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)

#3 /usr/html/wp-admin/includes/plugin.php(690): do_action('activate_static...', NULL)

#4 phar:///usr/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php(323): activate_plugin('static-html-out...', '', NULL)

#5 [internal function]: Plugin_Command->activate(Array, Array)

#6 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)

#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Ar in /usr/html/wp-content/plugins/static-html-output-plugin/src/Controller.php on line 115

Fatal error: Uncaught TypeError: Argument 1 passed to StaticHTMLOutput\Controller::activate() must be of the type bool, null given, called in /usr/html/wp-includes/class-wp-hook.php on line 287 and defined in /usr/html/wp-content/plugins/static-html-output-plugin/src/Controller.php:115

Warning: Plugin 'simplerstatic' is already active.

Success: Plugin already activated.

2020/05/19 04:43:32 [notice] 69#69: using the "epoll" event method

2020/05/19 04:43:32 [notice] 69#69: nginx/1.16.1

2020/05/19 04:43:32 [notice] 69#69: OS: Linux 4.19.76-linuxkit

2020/05/19 04:43:32 [notice] 69#69: getrlimit(RLIMIT_NOFILE): 1048576:1048576

2020/05/19 04:43:32 [notice] 69#69: start worker processes

2020/05/19 04:43:32 [notice] 69#69: start worker process 70

running script

[i] Fixing permissions...

waiting for mysql to be available...

2020-05-19 4:45:31 0 [Note] /usr/bin/mysqld (mysqld 10.4.13-MariaDB) starting as process 15 ...

2020-05-19 4:45:31 0 [Note] InnoDB: Using Linux native AIO

2020-05-19 4:45:31 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins

2020-05-19 4:45:31 0 [Note] InnoDB: Uses event mutexes

2020-05-19 4:45:31 0 [Note] InnoDB: Compressed tables use zlib 1.2.11

2020-05-19 4:45:31 0 [Note] InnoDB: Number of pools: 1

2020-05-19 4:45:31 0 [Note] InnoDB: Using SSE2 crc32 instructions

2020-05-19 4:45:31 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts)

2020-05-19 4:45:31 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M

2020-05-19 4:45:31 0 [Note] InnoDB: Completed initialization of buffer pool

2020-05-19 4:45:31 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().

2020-05-19 4:45:31 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=1504155

2020-05-19 4:45:31 0 [Note] InnoDB: 128 out of 128 rollback segments are active.

2020-05-19 4:45:31 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"

2020-05-19 4:45:31 0 [Note] InnoDB: Creating shared tablespace for temporary tables

2020-05-19 4:45:31 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...

2020-05-19 4:45:31 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.

2020-05-19 4:45:31 0 [Note] InnoDB: Waiting for purge to start

2020-05-19 4:45:31 0 [Note] InnoDB: 10.4.13 started; log sequence number 1504164; transaction id 753

2020-05-19 4:45:31 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool

2020-05-19 4:45:31 0 [Note] Plugin 'FEEDBACK' is disabled.

2020-05-19 4:45:31 0 [Note] InnoDB: Buffer pool(s) load completed at 200519 4:45:31

2020-05-19 4:45:31 0 [Note] Reading of all Master_info entries succeeded

2020-05-19 4:45:31 0 [Note] Added new Master_info '' to hash table

2020-05-19 4:45:31 0 [Note] /usr/bin/mysqld: ready for connections.

Version: '10.4.13-MariaDB' socket: '/run/mysqld/mysqld.sock' port: 0 MariaDB Server

2020-05-19 4:45:32 8 [Warning] Access denied for user 'root'@'localhost' (using password: NO)

2020-05-19 4:45:32 9 [Warning] Access denied for user 'root'@'localhost' (using password: NO)

ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

Error: The 'wp-config.php' file already exists.

rm: can't remove 'wp-config-sample.php': No such file or directory

WordPress is already installed.

Success: Rewrite structure set.

Success: Rewrite rules flushed.

Success: Value passed for 'blogdescription' option is unchanged.

Success: Updated post 1.

2020/05/19 04:45:34 [notice] 69#69: using the "epoll" event method

2020/05/19 04:45:34 [notice] 69#69: nginx/1.16.1

2020/05/19 04:45:34 [notice] 69#69: OS: Linux 4.19.76-linuxkit

2020/05/19 04:45:34 [notice] 69#69: getrlimit(RLIMIT_NOFILE): 1048576:1048576

2020/05/19 04:45:34 [notice] 69#69: start worker processes

2020/05/19 04:45:34 [notice] 69#69: start worker process 70

2020/05/19 06:12:48 [notice] 69#69: signal 15 (SIGTERM) received, exiting

2020/05/19 06:12:48 [notice] 70#70: signal 15 (SIGTERM) received, exiting

2020/05/19 06:12:48 [notice] 70#70: exiting

2020/05/19 06:12:48 [notice] 70#70: exit

2020-05-19 14:52:51 0 [Note] /usr/bin/mysqld (mysqld 10.4.13-MariaDB) starting as process 15 ...

2020-05-19 14:52:51 0 [Note] InnoDB: Using Linux native AIO

2020-05-19 14:52:51 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins

2020-05-19 14:52:51 0 [Note] InnoDB: Uses event mutexes

2020-05-19 14:52:51 0 [Note] InnoDB: Compressed tables use zlib 1.2.11

2020-05-19 14:52:51 0 [Note] InnoDB: Number of pools: 1

2020-05-19 14:52:51 0 [Note] InnoDB: Using SSE2 crc32 instructions

2020-05-19 14:52:51 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts)

2020-05-19 14:52:51 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M

2020-05-19 14:52:51 0 [Note] InnoDB: Completed initialization of buffer pool

2020-05-19 14:52:51 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().

2020-05-19 14:52:51 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=1522608

2020-05-19 14:52:51 0 [Note] InnoDB: 128 out of 128 rollback segments are active.

2020-05-19 14:52:51 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"

2020-05-19 14:52:51 0 [Note] InnoDB: Creating shared tablespace for temporary tables

2020-05-19 14:52:51 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...

2020-05-19 14:52:51 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.

2020-05-19 14:52:51 0 [Note] InnoDB: Waiting for purge to start

2020-05-19 14:52:51 0 [Note] InnoDB: 10.4.13 started; log sequence number 1522617; transaction id 771

2020-05-19 14:52:51 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool

2020-05-19 14:52:51 0 [Note] Plugin 'FEEDBACK' is disabled.

2020-05-19 14:52:51 0 [Note] InnoDB: Buffer pool(s) load completed at 200519 14:52:51

2020-05-19 14:52:51 0 [Note] Reading of all Master_info entries succeeded

2020-05-19 14:52:51 0 [Note] Added new Master_info '' to hash table

2020-05-19 14:52:51 0 [Note] /usr/bin/mysqld: ready for connections.

2020-05-19 14:52:51 8 [Warning] Access denied for user 'root'@'localhost' (using password: NO)

2020-05-19 14:52:51 9 [Warning] Access denied for user 'root'@'localhost' (using password: NO)

2020/05/19 14:52:53 [notice] 69#69: using the "epoll" event method

2020/05/19 14:52:53 [notice] 69#69: nginx/1.16.1

2020/05/19 14:52:53 [notice] 69#69: OS: Linux 4.19.76-linuxkit

2020/05/19 14:52:53 [notice] 69#69: getrlimit(RLIMIT_NOFILE): 1048576:1048576

2020/05/19 14:52:53 [notice] 69#69: start worker processes

2020/05/19 14:52:53 [notice] 69#69: start worker process 70

2020/05/19 15:25:06 [warn] 70#70: *457 a client request body is buffered to a temporary file /tmp/nginx/body/1/00/0000000001, client: 172.17.0.1, server: , request: "POST /wp-admin/update.php?action=upload-plugin HTTP/1.1", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/plugin-install.php"

2020/05/19 15:31:45 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'StaticHTMLOutput\BunnyCDN' does not have a method 'test_bunny' in /usr/html/wp-content/plugins/static-html-output-plugin/static-html-output-plugin.php on line 106" while reading upstream, client: 172.17.0.1, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/admin.php?page=statichtmloutput"

2020/05/19 15:32:17 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'StaticHTMLOutput\BunnyCDN' does not have a method 'bunnycdn_prepare_export' in /usr/html/wp-content/plugins/static-html-output-plugin/static-html-output-plugin.php on line 106" while reading upstream, client: 172.17.0.1, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/admin.php?page=statichtmloutput"

2020/05/19 15:32:17 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to a member function putWithFileStreamAndHeaders() on null in /usr/html/wp-content/plugins/static-html-output-plugin/src/BunnyCDN.php:258

#0 /usr/html/wp-content/plugins/static-html-output-plugin/src/BunnyCDN.php(117): StaticHTMLOutput\BunnyCDN->createFileInBunnyCDN()

#1 /usr/html/wp-content/plugins/static-html-output-plugin/src/BunnyCDN.php(54): StaticHTMLOutput\BunnyCDN->upload_files()

#2 /usr/html/wp-content/plugins/static-html-output-plugin/static-html-output-plugin.php(100): StaticHTMLOutput\BunnyCDN->__construct()

#3 /usr/html/wp-includes/class-wp-hook.php(287): static_html_output_ajax('')

#4 /usr/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)

#5 /usr/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)

#6 /usr/html/wp-admin/admin-ajax.php(175): do_action('wp_ajax_wp_stat...')



#7 {main}

thrown in /usr/html/wp-content/plugins/static-html-output-plugin/src/BunnyCDN.php on line 258" while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/admin.php?page=statichtmloutput"

2020/05/19 15:32:38 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'StaticHTMLOutput\BunnyCDN' does not have a method 'bunnycdn_prepare_export' in /usr/html/wp-content/plugins/static-html-output-plugin/static-html-output-plugin.php on line 106" while reading upstream, client: 172.17.0.1, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/admin.php?page=statichtmloutput"

2020/05/19 15:32:38 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to a member function putWithFileStreamAndHeaders() on null in /usr/html/wp-content/plugins/static-html-output-plugin/src/BunnyCDN.php:258

2020/05/19 15:33:17 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'StaticHTMLOutput\BunnyCDN' does not have a method 'test_bunny' in /usr/html/wp-content/plugins/static-html-output-plugin/static-html-output-plugin.php on line 106" while reading upstream, client: 172.17.0.1, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/admin.php?page=statichtmloutput"

2020/05/19 15:33:22 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'StaticHTMLOutput\BunnyCDN' does not have a method 'test_bunny' in /usr/html/wp-content/plugins/static-html-output-plugin/static-html-output-plugin.php on line 106" while reading upstream, client: 172.17.0.1, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/admin.php?page=statichtmloutput"

2020/05/19 15:33:36 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'StaticHTMLOutput\BunnyCDN' does not have a method 'bunnycdn_prepare_export' in /usr/html/wp-content/plugins/static-html-output-plugin/static-html-output-plugin.php on line 106" while reading upstream, client: 172.17.0.1, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/admin.php?page=statichtmloutput"

2020/05/19 15:33:36 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to a member function putWithFileStreamAndHeaders() on null in /usr/html/wp-content/plugins/static-html-output-plugin/src/BunnyCDN.php:258

2020/05/19 15:34:12 [warn] 70#70: *484 a client request body is buffered to a temporary file /tmp/nginx/body/2/00/0000000002, client: 172.17.0.1, server: , request: "POST /wp-admin/update.php?action=upload-plugin HTTP/1.1", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/plugin-install.php"

2020/05/19 15:35:44 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'StaticHTMLOutput\BunnyCDN' does not have a method 'test_bunny' in /usr/html/wp-content/plugins/static-html-output-plugin/static-html-output-plugin.php on line 106" while reading upstream, client: 172.17.0.1, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/admin.php?page=statichtmloutput"

2020/05/19 15:36:17 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'StaticHTMLOutput\BunnyCDN' does not have a method 'bunnycdn_prepare_export' in /usr/html/wp-content/plugins/static-html-output-plugin/static-html-output-plugin.php on line 106" while reading upstream, client: 172.17.0.1, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/admin.php?page=statichtmloutput"

2020/05/19 15:36:17 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to a member function putWithFileStreamAndHeaders() on null in /usr/html/wp-content/plugins/static-html-output-plugin/src/BunnyCDN.php:258

2020/05/19 15:39:15 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught StaticHTMLOutput\StaticHTMLOutputException: StaticHTMLOutput\StaticHTMLOutputException: BunnyCDN API bad response status in /usr/html/wp-content/plugins/static-html-output-plugin/src/BunnyCDN.php:237

#0 /usr/html/wp-content/plugins/static-html-output-plugin/src/BunnyCDN.php(60): StaticHTMLOutput\BunnyCDN->test_deploy()

#1 /usr/html/wp-content/plugins/static-html-output-plugin/static-html-output-plugin.php(100): StaticHTMLOutput\BunnyCDN->__construct()

#2 /usr/html/wp-includes/class-wp-hook.php(287): static_html_output_ajax('')

#3 /usr/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)

#4 /usr/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)

#5 /usr/html/wp-admin/admin-ajax.php(175): do_action('wp_ajax_wp_stat...')

#6 {main} in /usr/html/wp-content/plugins/static-html-output-plugin/src/BunnyCDN.php:242

#0 /usr/html/wp-content/plugins/static-html-output-plugin/src/BunnyCDN.php(60): StaticHTMLOutput\BunnyCDN-" while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/admin.php?page=statichtmloutput"

2020/05/19 15:39:59 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'StaticHTMLOutput\BunnyCDN' does not have a method 'test_bunny' in /usr/html/wp-content/plugins/static-html-output-plugin/static-html-output-plugin.php on line 106" while reading upstream, client: 172.17.0.1, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/admin.php?page=statichtmloutput"

2020/05/19 15:40:37 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'StaticHTMLOutput\BunnyCDN' does not have a method 'bunnycdn_prepare_export' in /usr/html/wp-content/plugins/static-html-output-plugin/static-html-output-plugin.php on line 106" while reading upstream, client: 172.17.0.1, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "gulshan.localhost:4067", referrer: "http://gulshan.localhost:4067/wp-admin/admin.php?page=statichtmloutput"

2020/05/19 15:40:37 [error] 70#70: *484 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to a member function putWithFileStreamAndHeaders() on null in /usr/html/wp-content/plugins/static-html-output-plugin/src/BunnyCDN.php:258

```

**Comment by leonstafford** [comment]
Ah, many thanks! I'll dig in and do a full deploy and fix the broken bits - seems some recent code cleanup / renamings at fault

**Comment by thegulshankumar** [comment]
Please take your time. Thanks
